name:                tetris-hs
version:             0.1.0.0
github:              "nanikit/tetris-hs"
license:             BSD3
author:              "nanikit"
maintainer:          "nanikit4@gmail.com"
copyright:           "2019 nanikit"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Tetris on windows (SDL2)
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tetris-hs#readme>

default-extensions:
- FlexibleContexts
- ImportQualifiedPost
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables

dependencies:
- base
# Prelude replacement
- rio
- random
- vector
# GUI
- sdl2
- sdl2-ttf
# SDL2 functions use this as parameter
- linear

library:
  source-dirs: src
  when:
    - condition: flag(dev)
      cpp-options:
      - -DDEV

executables:
  tetris:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
      - condition: flag(dev)
        ghc-options:
        - -optl-Wl,--subsystem,console
    dependencies:
    - tetris-hs

tests:
  spec:
    defaults:            hspec/hspec@main
    dependencies:
    - tetris-hs

flags:
  dev:
    description: Use console for debug
    manual: true
    default: false
